# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliasSampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AliasSampleProject
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Font-Awesome-Swift', '~> 1.7.2'

  target 'AliasSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AliasSampleProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
